### ISSUE TITLE
При открытии приложения появляется ошибка

### ISSUE THREAD

**Issue by mak7im01** [Communist02/AnimePlayer#10]
Здравствуйте. При открытии приложения появляется ошибка в установочной версии и в портабл
![Снимок экрана](https://github.com/user-attachments/assets/3ffa1fb1-3416-476f-9747-4f2c15d16e65)

**Comment by Communist02** [comment]
Возможно у вас очень старый процессор. Попробуйте поменять файл libmpv-2.dll
Я положил библиотеку v3, которая требует инструкции современного процессора (avx avx2 bmi bmi2 fma lzcnt movbe sse3 sse4 sse4.1 sse4.2 ssse3 xsave sahf mwait crc32 cx16 popcnt f16c).
Поменяйте на версию без v3 отсюда: https://sourceforge.net/projects/mpv-player-windows/files/libmpv/
Например: https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20240811-git-4e50da3.7z/download
Если не поможет, то попробуйте установить Microsoft Visual C++ Redistributable: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by mak7im01** [comment]
Большое Вам спасибо. Файл по ссылке помог
