### ISSUE TITLE
Idea: Allow for offline encoding

### ISSUE THREAD

**Issue by ThatPlasma** [Communist02/AnimePlayer#4]
The ability to encoding video with the sharders at resolutions of 2x

**Comment by Communist02** [comment]
The idea is good, but it will be quite difficult to implement. Maybe in the future I will make this feature.
For now, you can use this program to encode video with quality enhancement:
[Squirrel Anime Enhance](https://github.com/Justin62628/Squirrel-RIFE/releases/tag/v3.20.4)
It uses a neural network, not shaders. So encoding will take much longer, but the quality will be better.

**Comment by ThatPlasma** [comment]
yeah just my pc is slow you know cant even handle the Anime4k L
