### ISSUE TITLE
how do I open it via the console?

### ISSUE THREAD

**Issue by lanceqqe** [Communist02/AnimePlayer#8]
how do I open it via the console?  mpv supports such functionality, but can this player do it? Может ли этот плеер открываться через cmd?

**Comment by lanceqqe** [comment]
Он не воспринимает параметры запуска, если их задавать через консоль, а не внутри самого плеера. Ну либо я что-то не так делаю.

**Comment by Communist02** [comment]
Если вы говорите про просто открыть файл или папку, то все должно работать. Например, для открытия файла можно использовать:      "C:\Program Files (x86)\Anime Player\AnimePlayer.exe" C:\Users\Denis\Videos\Rocker.mp4         Если вы говорите про что-то такого вида "C:\Program Files (x86)\Anime Player\AnimePlayer.exe" --volume=0    , то такого функционала на данный момент нет. Если Вам это очень нужно, то можете написать в параметрах запуска в приложении     exec(sys.argv[2])     и запускать через cmd примерно так:       "C:\Program Files (x86)\Anime Player\AnimePlayer.exe" C:\Users\Denis\Videos\Rocker.mp4 "player.volume=50; player.time_pos = 500"         Если видео не нужно запускать, то напишите пустые кавычки:           "C:\Program Files (x86)\Anime Player\AnimePlayer.exe" "" "player.volume=50; player.time_pos = 500"

Google Translate:
If you are talking about just opening a file or folder, then everything should work. For example, to open a file you can use:          "C:\Program Files (x86)\Anime Player\AnimePlayer.exe" C:\Users\Denis\Videos\Rocker.mp4           If you are talking about something like this        "C:\ Program Files (x86)\Anime Player\AnimePlayer.exe" --volume=0            , then there is no such functionality at the moment. If you really need this, you can write exec(sys.argv[2]) in the launch parameters of the application and run it via cmd something like this:         "C:\Program Files (x86)\Anime Player\AnimePlayer.exe" C:\ Users\Denis\Videos\Rocker.mp4 "player.volume=50; player.time_pos = 500"         If the video does not need to be launched, then write empty quotes:             "C:\Program Files (x86)\Anime Player\AnimePlayer.exe" "" "player.volume=50; player.time_pos = 500"
