### ISSUE TITLE
Поддержка переключения аудиодорожек

### ISSUE THREAD

**Issue by riptovskiy** [Communist02/AnimePlayer#9]
В первую очередь хочу выразить благодарность за плеер, очень удобно очень классно всё, спасибо)

Лично я не нашёл ничего для того чтобы переключить аудиодорожку воспроизводимого файла следовательно предполагаю что такого функционала просто нет, но как бы часто бывает такое что в скачанной анимке их несколько и нужна какая нибудь не та что воспроизводится автоматически по умолчанию.

Заранее спасибо.
<3

**Comment by Communist02** [comment]
Данный функционал уже присутствует!
https://github.com/Communist02/AnimePlayer/assets/63093786/46d866f9-b9bd-4313-879c-6f922efe05b8
Иногда могут не показываться дорожки, если информация о видео не загрузилась за 5 сек (3 сек локальный файл). Локальные файлы обычно всегда успевают загружаться, а вот по ссылке не всегда. Я попробую решить эту проблему в будущих релизах. Я переписывал плеер с другого графического фреймворка, где эта проблема была нерешаема, поэтому с того времени и осталась эта проблема. Наверно еще уберу возможное провисание плеера при загрузке видео по ссылке. Ведь плеер именно поэтому и провисает, что ждет эти 5 секунд на загрузку информации о дорожках.

**Comment by riptovskiy** [comment]
Емаё блин а я чё то и не доперил даже что там такая штука есть, +реп за видос в плеере ахах)
тогда респект и уважуха вопрос полностью снят, мой косяк что не приметил.
